[info]
relay_url = "wss://nostr.itsnebula.net/"
name = "nebula-relay"
description = "Nebula's Nostr relay"
relay_icon = "https://itsnebula.net/favicon.png"

[diagnostics]

[database]
engine = "sqlite"
max_conn = 2

[logging]

[grpc]

[network]
address = "0.0.0.0"
port = 4629

[options]
reject_future_seconds = 1800

[limits]
messages_per_sec = 0      # 5 for public
subscriptions_per_min = 0 # 5 for public
limit_scrapers = true

[authorization]
pubkey_whitelist = [
    "a4e2add42ff05ce46b7751bb7ac8e646b74699bdd061d9a99dfa20fae13458b6",
]

[verified_users]

[pay_to_relay]
